In [8]:
import torch 
import torch.nn as nn
import torch.optim as optim 

In [5]:
logits=torch.tensor([[2.5,0.4,1.1],[0.1,2.2,0.6],[0.3,0.3,3.0]])
softmax_prob=torch.softmax(logits,dim=1)
print(softmax_prob)

tensor([[0.7304, 0.0894, 0.1801],
        [0.0925, 0.7551, 0.1524],
        [0.0592, 0.0592, 0.8815]])


In [11]:
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        self.layer1=nn.Linear(input_size,hidden_size)
        self.LeakyRelu=nn.LeakyReLU(negative_slope=0.01)
        self.layer2=nn.Linear(hidden_size,output_size) 
    def forward(self, x):
        x=self.layer1(x)
        x=self.LeakyRelu(x)
        x=self.layer2(x)
        return x 

input_size=10
hidden_size=20
output_size=1 
model=SimpleNN(input_size,hidden_size,output_size)

input_data=torch.randn(5,input_size)
output_data=model(input_data)

print(input_data)
print(output_data)

tensor([[-0.6494, -0.7484,  1.6158,  1.0068, -0.2692, -0.5109, -1.0181,  1.2440,
         -0.2004, -0.5286],
        [ 0.1508, -0.3302, -1.3023,  0.0789,  0.5229, -1.2363, -0.9909, -0.4400,
          1.7709, -0.7649],
        [ 0.6456, -0.7784, -1.0425,  0.7099,  0.2006, -2.1459,  1.8500,  0.7816,
         -0.6889, -0.3856],
        [-1.3879, -0.2654,  0.7746, -0.9139,  1.4343,  0.5331, -0.2995, -1.2982,
          0.6372,  0.7080],
        [ 0.9612, -3.0125, -0.7989, -0.7558, -1.7954,  1.1015, -0.5800, -0.0836,
          0.5474, -0.2131]])
tensor([[-0.1458],
        [-0.0514],
        [ 0.5012],
        [-0.0305],
        [ 0.1211]], grad_fn=<AddmmBackward0>)


In [12]:
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        self.layer1=nn.Linear(input_size,hidden_size)
        self.layer2=nn.Linear(hidden_size,output_size) 
    def forward(self, x):
        x_relu=torch.relu(self.layer1(x))
        x_selu=torch.selu(self.layer2(x_relu))
        return x_relu, x_selu 
    
input_size=10
hidden_size=20
output_size=1 
model=SimpleNN(input_size,hidden_size,output_size)

input_data=torch.randn(5,input_size)
output_relu, output_selu=model(input_data) 
print(input_data,output_relu,output_selu)

tensor([[ 0.7085, -0.2441,  0.5331,  0.6369,  0.1714, -0.3857, -1.2689, -0.8714,
         -1.6795, -1.2297],
        [-0.0833,  0.2919,  1.0622,  1.0229,  0.0563,  0.3724, -0.4013, -0.5853,
          0.3315,  1.6280],
        [-0.6985, -0.1723, -0.8333, -0.5684, -1.5114, -0.8745, -0.1090, -0.0046,
          1.0568, -0.2431],
        [-0.6273,  1.3734, -0.9415, -0.3201,  0.2490,  0.3934,  1.0258,  0.9608,
          1.6735, -1.3320],
        [ 1.2307,  1.4004,  0.7791,  0.5741,  0.5453, -0.6274, -0.0358,  1.3453,
         -0.8096, -0.6439]]) tensor([[0.4088, 0.1420, 0.0320, 0.3373, 0.2980, 0.0000, 0.1216, 0.7735, 0.0582,
         0.0000, 0.0000, 0.0000, 0.0000, 0.1869, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.6229, 0.0000, 0.5802, 0.0000, 1.1322,
         0.0000, 0.0000, 0.0000, 0.1773, 0.0000, 1.3598, 0.0000, 0.6549, 0.2715,
         0.0560, 0.0000],
        [0.1769, 0.0000, 0.0000, 0.0000, 0.0000, 0.5662, 0.0000, 0.0000, 0.000