In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [3]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [4]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [5]:
0.55 * 0.43 + 0.87 * 0.15 + 0.66 * 0.89

0.9544

In [6]:
torch.dot(input_query, input_1)


tensor(0.9544)

In [9]:
res = 0

query1 = inputs[1]  
query2 = inputs[0]
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query1[idx]


i=3

res = torch.dot(inputs[i], input_query)

print(res)

tensor(0.8434)


In [10]:
query=inputs[1]

attn_scores_2=torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, input_query)

print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
