In [1]:
import torch 
import numpy as np

In [6]:
tensor_1=torch.tensor([1,2,3])
print(tensor_1)

tensor([1, 2, 3])


In [9]:
array_1=np.array([1,2,3])
array_1

array([1, 2, 3])

In [12]:
tensor_from_numpy=torch.tensor(array_1)

In [15]:
empty_tensor=torch.empty(3)
print("Empty Tensor", empty_tensor)

Empty Tensor tensor([1.2259e-20, 0.0000e+00, 0.0000e+00])


In [18]:
zero_tensor=torch.zeros(2,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
one_tensor=torch.ones(2,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
random_tensor=torch.rand(3,3)
random_tensor

tensor([[0.7006, 0.2633, 0.3417],
        [0.2635, 0.9024, 0.7718],
        [0.1540, 0.0616, 0.7506]])

In [24]:
arange_tensor=torch.arange(start=0,end=100,step=10)
arange_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
random_tensor[1,1]

tensor(0.9024)

In [26]:
random_tensor[1,:]

tensor([0.2635, 0.9024, 0.7718])

In [27]:
random_tensor[:,0]

tensor([0.7006, 0.2635, 0.1540])

In [28]:
random_tensor[1,1].item()

0.9024404287338257

In [31]:
reshape_tensor=torch.rand(5,4)
reshape_tensor

tensor([[0.0569, 0.0535, 0.3403, 0.5436],
        [0.5039, 0.1612, 0.4421, 0.4873],
        [0.0152, 0.2037, 0.6822, 0.6863],
        [0.1036, 0.9367, 0.5917, 0.2556],
        [0.9656, 0.5745, 0.9991, 0.1957]])

In [32]:
new_reshape_tensor=reshape_tensor.view(-1,2)
new_reshape_tensor

tensor([[0.0569, 0.0535],
        [0.3403, 0.5436],
        [0.5039, 0.1612],
        [0.4421, 0.4873],
        [0.0152, 0.2037],
        [0.6822, 0.6863],
        [0.1036, 0.9367],
        [0.5917, 0.2556],
        [0.9656, 0.5745],
        [0.9991, 0.1957]])

In [36]:
tensor_a=torch.tensor([1, 2, 3])
tensor_b=torch.tensor([2,4,6])
results_add_1=torch.add(tensor_b, tensor_a)
results_add_2=tensor_b + tensor_a
results_sub_1=tensor_b-tensor_a 

print(results_add_1)
print(results_add_2)
print(results_sub_1)

tensor([3, 6, 9])
tensor([3, 6, 9])
tensor([1, 2, 3])


In [43]:
tensor_b.add_(tensor_a)
tensor_b

tensor([ 9, 18, 27])

In [44]:
matrix_a=torch.tensor([[1,2], [3,4]])
matrix_b=torch.tensor([[5,6], [7,8]])

In [48]:
results_multiply=torch.mm(matrix_a,matrix_b)
print(results_multiply)

tensor([[19, 22],
        [43, 50]])


In [50]:
results_multiply2=torch.mul(matrix_a,matrix_b)
print(results_multiply2)

tensor([[ 5, 12],
        [21, 32]])


In [51]:
results_multiply.dtype

torch.int64

In [52]:
random_tensor.dtype

torch.float32

In [53]:
tensor_int=torch.tensor([4,5,6], dtype=torch.int64)


In [55]:
print(tensor_int.dtype)

torch.int64


In [56]:
tensor_float=tensor_int.to(torch.float32)

In [57]:
print(tensor_float.dtype)

torch.float32


In [58]:
print(tensor_float)

tensor([4., 5., 6.])


In [59]:
tensor_float.device

device(type='cpu')

In [60]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [61]:
tensor_float.to(device)

tensor([4., 5., 6.])

In [62]:
tensor_new=torch.tensor([51.50,46.2], dtype=torch.float32)

In [63]:
tensor_new.shape

torch.Size([2])