In [1]:
import numpy as np 
import torch

In [2]:
nv=np.array([[1,2,3,4]])
print(nv), print(' ')

print(nv.T), print(' ')

nvT=nv.T 
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [3]:
nM=np.array([[1,2,3,4],[5,6,7,8]])
print(nM), print(' ')

print(nM.T), print(' ')

nMT=nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
tv=torch.tensor([[1,2,3,4]])
print(tv), print(' ')

print(tv.T), print(' ')

tvT=tv.T 
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [5]:
nv1=np.array([1,2,3,4])
nv2=np.array([0,1,0,-1])

print(np.dot(nv1,nv2))

print(np.sum(nv1*nv2))


-2
-2


In [6]:
tv1=torch.tensor([1,2,3,4])
tv2=torch.tensor([0,1,0,-1])

print(torch.dot(tv1,tv2))
print(torch.sum(tv1*tv2))

tensor(-2)
tensor(-2)


In [12]:
A=np.random.randn(3,4)
B=np.random.randn(4,5)
C=np.random.randn(3,7)

print(np.round(A@B, 2)), print(' ')
# print(np.round(A@C),2), print(' ')
print(np.round(C.T@A,2))

[[ 1.37 -2.7  -0.32  0.    1.26]
 [ 4.7   0.49  0.94  0.93  1.92]
 [ 3.3  -0.42 -0.25  0.75  1.37]]
 
[[-2.05  0.84 -1.6   0.67]
 [-1.4   0.03 -0.77  0.51]
 [ 2.   -1.36  1.29 -0.31]
 [-3.    1.86 -2.2   0.67]
 [-1.79 -0.11 -2.48  1.45]
 [ 0.92 -0.31 -1.52  0.79]
 [ 1.57  0.05 -0.02 -0.16]]


In [13]:
A=torch.randn(3,4)
B=torch.randn(4,5)
C1=np.random.randn(4,7)
C2=torch.tensor(C1,dtype=torch.float)

print(np.round(A@B,2))
print(np.round(A@C1,2))

tensor([[-2.1300,  0.7600,  1.0800, -1.5300,  0.4200],
        [-2.1500,  1.6500,  1.0200,  0.3500, -1.9900],
        [-2.3300,  0.3200,  1.5300, -1.4300,  0.2900]])
tensor([[ 0.2800, -0.6300, -1.6200,  2.6200,  2.2500,  1.7800,  0.4900],
        [-2.3600, -0.2600, -0.1800,  2.3100,  1.8300,  0.6700,  0.1800],
        [ 1.3200, -1.3300, -2.1400,  3.0200,  1.1100,  1.0600,  1.0300]],
       dtype=torch.float64)


/tmp/ipykernel_4768/1812895568.py:7: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round(A@C1,2))
