In [8]:
import numpy as np 
import torch 
import torch.nn as nn

In [9]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3)
)

deepnet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3)
)

print(widenet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)


In [10]:
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[-0.6463,  0.0590],
        [ 0.2926,  0.1440]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.4371,  0.3099], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.0973,  0.3784],
        [ 0.4539, -0.6655]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([0.0711, 0.3565], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[ 0.6783,  0.5223],
        [-0.6719,  0.6293],
        [-0.1248,  0.1745]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.3707, -0.2058, -0.2776], requires_grad=True))
 


In [12]:
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide+=len(p[1])

numNodesInWide

7

In [13]:
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)
     


This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [15]:
nparams = np.sum([p.numel() for p in widenet.parameters() if p.requires_grad])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [ ]:
# from torchsummary import summary
# summary(widenet,(1,2))



ModuleNotFoundError: No module named 'torchsummary'