In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

     

In [4]:
prob=.5
dropout=nn.Dropout(p=prob)
x=torch.ones(10)

y=dropout(x)
print(y)
int(torch.mean(y))

tensor([2., 0., 2., 2., 2., 2., 2., 0., 2., 0.])


1

In [8]:
dropout.eval()
# y=F.dropout(x,training=True)
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [10]:
dropout.train()
y=dropout(x)
print(y)


tensor([2., 0., 0., 2., 0., 2., 0., 0., 0., 2.])
