In [ ]:
import torch 
import numpy as np 
import matplotlib.pyplot as plt 

In [ ]:
np.random.randn(5)


array([ 0.70598044,  2.42441733,  0.34616505,  0.75298444, -2.53988265])

In [56]:
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]


In [44]:
randseed1=np.random.RandomState(17)
randseed2=np.random.RandomState(20210530)
print(randseed1.randn(5))
print(randseed2.randn(5))
print(randseed1.randn(5))
print(randseed2.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 1.13072645  0.56003969 -0.6183973  -0.22479872  2.21590145]


In [45]:
torch.randn(5)

tensor([ 0.7893, -0.6459,  2.5522,  2.4915, -0.0497])

In [51]:
torch.manual_seed(17)
print(torch.randn(5))

print(np.random.randn(5))

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.03260213  2.52525474 -0.17490347 -0.84195834  0.07660079]
